<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $page_title;?></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" type="text/css" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="http://localhost:8000/asset/style.css" />
<style>
@charset "utf-8";
/* CSS Document */
div.page-wrapper{padding:20px;}
div.content-wrapper{margin:0px auto;width:1180px;}
div.artist-list-wrapper{width:100%;}
div.artist-wrapper{width:100%; padding:10px 0px;border-bottom:1px solid #999;}
div.artist-data{padding:0px 10px;}
div.artist-name{}
div.display-block{display:inline-block;}
div.pagination{float:right;} 
ul.page-link{border:0px none;} 
ul.page-link li{list-style:none; display:inline-block;} 
div.artist-info-image{float:left;min-width:300px;padding:0 50px 50px 0px;background:#FFFFFF;}
div.artist-info-contents{}
div.artist-info-name{border-bottom:1px solid #999;}
div.artist-info-public{text-align:right;padding:10px 0px;}
h5.sub-head{padding-top:10px;}
</style>
</head>

<body>
<div class="content-wrapper">